<%@ page language="java" contentType="text/html; charset=UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="path" value="${pageContext.request.contextPath}" />
<html>
<head>
<link href="../../resouces/css/style.css" rel="stylesheet"
	type="text/css">
<link href="../../resouces/css/iconStyle.css" rel="stylesheet"
	type="text/css">
<script type="text/javascript" src="../../resouces/js/main.js"></script>
<script type="text/javascript"
	src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
<link rel="stylesheet" href="path/to/fontello/css/fontello.css">
<link rel="stylesheet" href="path/to/fontello/css/animation.css">
<title>WelCome.</title>
</head>
<body class="welcome-body">
	<div class="jb-content">
		<div class="jb-container">

			<div class="jb-header">
				<h1>
					김 근호
				</h1>
			</div>
			<div class="jb-main">
				<p>컴퓨터는 거짓말을 하지 않는다.</p>
			</div>
			<div class="jb-footer">
				<div class="container" id="icons">
					<div class="row">
						<div class="span3" title="Code: 0xe801">
							<i class="demo-icon icon-user"></i> <span class="i-name"><a href="index">Kim Geunho</a></span>
							<span class="i-code">0xe801</span>
						</div>
						<div class="span3" title="Code: 0xe800">
							<i class="demo-icon icon-mail"></i> <span class="i-name"><a href="mailto:﻿"asdlkjd1@naver.com">asdlkjd1@naver.com</a></span>
							<span class="i-code">0xe800</span>
						</div>
						<div class="span3" title="Code: 0xf1d2">
							<i class="demo-icon icon-git-squared"></i> <span class="i-name"><a href="https://github.com/kimkgh8">https://github.com/kimkgh8</a></span>
							<span class="i-code">0xf1d2</span>
						</div>
					</div>
					<div class="container footer">
						developer by <span class="i-name">KIM GEUNHO</span>
					</div> 
				</div>
			</div>
		</div>
	</div>

	<div class="jb-content">
		<div class="jb-container">
			<div class="jb-header">
				<h1>
					김 근호
				</h1>
			</div>
			<div class="jb-main">
				<p>개발자의 길을 걸으면서 들은 생각입니다. 소스 안에 항상 답이 있다고 생각합니다.</p>
			</div>
			<div class="jb-footer">
				<div class="container" id="icons">
					<div class="row">
						<div class="span3" title="Code: 0xe801">
							<i class="demo-icon icon-user"></i> <span class="i-name"><a href="index">Kim Geunho</a></span>
							<span class="i-code">0xe801</span>
						</div>
						<div class="span3" title="Code: 0xe800">
							<i class="demo-icon icon-mail"></i> <span class="i-name"><a href="mailto:﻿"asdlkjd1@naver.com">asdlkjd1@naver.com</a></span>
							<span class="i-code">0xe800</span>
						</div>
						<div class="span3" title="Code: 0xf1d2">
							<i class="demo-icon icon-git-squared"></i> <span class="i-name"><a href="https://github.com/kimkgh8">https://github.com/kimkgh8</a></span>
							<span class="i-code">0xf1d2</span>
						</div>
					</div>
					<div class="container footer">
						Generated by <a href="https://fontello.com">fontello.com</a>
						developer by <span class="i-name">KIM GEUNHO</span> 
					</div> 
				</div>
			</div>
		</div>
	</div>
</body>
</html>
